### PR TITLE
UPDATED README.md to add information around PostGIS versioning and in…

### PR DESCRIPTION
**Pull request by cadecameron**
…stallation.

### CODE REVIEW

**Comment by cadecameron** [comment]
@Rovack 
Made some minor changes to the README.md file, regarding PostGIS versioning.

**Comment by Rovack** [comment]
Thanks @cadecameron , looks good to me.
Just to make sure: Was the breaking change actually in 2.2.0, or was it already in 2.0.0?

**Comment by cadecameron** [comment]
@Rovack , it looks like 2.2.0 (though I read somewhere that the old naming convention was supported up until 3.0):
https://postgis.net/docs/ST_DistanceSphere.html

**Comment by Rovack** [comment]
Huh, very unusual to be making breaking changes like that on a minor version, but alright.

**Pull request merged**
